name: Publish NuGet Package

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Install dependencies
        run: dotnet restore src/Calabonga.PagedListCore.Json.Tests.slnx

      - name: Build
        run: dotnet build src/Calabonga.PagedListCore.Json.Tests.slnx --configuration Release --no-restore

      - name: Test
        run: dotnet test src/Calabonga.PagedListCore.Json.Tests.slnx --configuration Release --no-build --verbosity normal

      - name: Build the NuGet package
        run: dotnet pack src/Calabonga.PagedListCore.Json.slnx --configuration Release --no-build --output ${{ github.workspace }}/nupkgs

      - name: Publish NuGet Package
        shell: pwsh
        run: |
          $package = Get-ChildItem -Path "${{ github.workspace }}/nupkgs" -Filter *.nupkg | Select-Object -First 1
          dotnet nuget push $package.FullName --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
